global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'velora_laravel'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:8000']
  - job_name: 'velora_node'
    static_configs:
      - targets: ['localhost:9100']
